// test/generate.test.js
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { generateScript } from '../lib/generate.js'

const base = {
  fields: ['model'],
  layout: 'single',
  colorStyle: 'monochrome',
  thresholds: { yellow: 50, red: 80 }
}

test('returns string starting with shebang', () => {
  assert.ok(generateScript(base).startsWith('#!/bin/bash'))
})

test('includes generated-by comment', () => {
  assert.ok(generateScript(base).includes('Generated by claude-statusline'))
  assert.ok(generateScript(base).includes('npx @alejandroroman/cc-statusline'))
})

test('monochrome omits ANSI color variables', () => {
  const s = generateScript({ ...base, colorStyle: 'monochrome' })
  assert.ok(!s.includes("G='\\033[32m'"))
})

test('traffic-light includes color variables', () => {
  const s = generateScript({ ...base, colorStyle: 'traffic-light' })
  assert.ok(s.includes("G='\\033[32m'"))
  assert.ok(s.includes("RED='\\033[31m'"))
})

test('custom thresholds appear in generated script', () => {
  const s = generateScript({ ...base, colorStyle: 'custom', thresholds: { yellow: 30, red: 60 } })
  assert.ok(s.includes('30'))
  assert.ok(s.includes('60'))
})

test('contextBar field includes bar() helper', () => {
  const s = generateScript({ ...base, fields: ['contextBar'] })
  assert.ok(s.includes('bar()'))
})

test('contextBar omitted when not in fields', () => {
  const s = generateScript({ ...base, fields: ['model'] })
  assert.ok(!s.includes('context:'))
})

test('rateLimitBars field reads native Claude Code rate limit fields', () => {
  const s = generateScript({ ...base, fields: ['rateLimitBars'] })
  assert.ok(s.includes('.rate_limits.five_hour.used_percentage'))
  assert.ok(s.includes('.rate_limits.seven_day.used_percentage'))
  assert.ok(!s.includes('api/oauth/usage'))
  assert.ok(!s.includes('Claude Code-credentials'))
})

test('no rateLimitBars means no reset time formatting logic', () => {
  const s = generateScript({ ...base, fields: ['model', 'contextBar'] })
  assert.ok(!s.includes('format_reset_time()'))
})

test('linesChanged field uses lines_added variable', () => {
  const s = generateScript({ ...base, fields: ['linesChanged'] })
  assert.ok(s.includes('lines_added'))
})

test('multi layout produces line1 and line2 variables', () => {
  const s = generateScript({ fields: ['model', 'contextBar'], layout: 'multi', colorStyle: 'monochrome', thresholds: { yellow: 50, red: 80 } })
  assert.ok(s.includes('line1='))
  assert.ok(s.includes('line2='))
})

test('single layout produces only line1 variable', () => {
  const s = generateScript({ fields: ['model', 'tokenCounts'], layout: 'single', colorStyle: 'monochrome', thresholds: { yellow: 50, red: 80 } })
  assert.ok(s.includes('line1='))
  assert.ok(!s.includes('line2='))
})

test('rateLimitBars field includes format_reset_time function', () => {
  const s = generateScript({ ...base, fields: ['rateLimitBars'] })
  assert.ok(s.includes('format_reset_time()'))
})

test('generated script renders native rate limit data from stdin', () => {
  const script = generateScript({
    fields: ['model', 'contextBar', 'rateLimitBars', 'resetTimes'],
    layout: 'multi',
    colorStyle: 'monochrome',
    thresholds: { yellow: 50, red: 80 }
  })
  const dir = mkdtempSync(join(tmpdir(), 'cc-statusline-test-'))
  const file = join(dir, 'statusline.sh')
  writeFileSync(file, script, { mode: 0o700 })

  try {
    const result = spawnSync('bash', [file], {
      input: JSON.stringify({
        model: { display_name: 'Opus' },
        context_window: { used_percentage: 25 },
        rate_limits: {
          five_hour: { used_percentage: 23.5, resets_at: 1738425600 },
          seven_day: { used_percentage: 41.2, resets_at: 1738857600 }
        }
      }),
      encoding: 'utf8',
    })

    assert.equal(result.status, 0, result.stderr)
    assert.match(result.stdout, /Opus/)
    assert.match(result.stdout, /context: .*25%/)
    assert.match(result.stdout, /5-hour: .*23%/)
    assert.match(result.stdout, /weekly: .*41%/)
    assert.match(result.stdout, /5-hour resets/)
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})
