// test/generate.test.js
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { generateScript } from '../lib/generate.js'

const base = {
  fields: ['model'],
  layout: 'single',
  colorStyle: 'monochrome',
  thresholds: { yellow: 50, red: 80 }
}

test('returns string starting with shebang', () => {
  assert.ok(generateScript(base).startsWith('#!/bin/bash'))
})

test('includes generated-by comment', () => {
  assert.ok(generateScript(base).includes('Generated by claude-statusline'))
})

test('monochrome omits ANSI color variables', () => {
  const s = generateScript({ ...base, colorStyle: 'monochrome' })
  assert.ok(!s.includes("G='\\033[32m'"))
})

test('traffic-light includes color variables', () => {
  const s = generateScript({ ...base, colorStyle: 'traffic-light' })
  assert.ok(s.includes("G='\\033[32m'"))
  assert.ok(s.includes("RED='\\033[31m'"))
})

test('custom thresholds appear in generated script', () => {
  const s = generateScript({ ...base, colorStyle: 'custom', thresholds: { yellow: 30, red: 60 } })
  assert.ok(s.includes('30'))
  assert.ok(s.includes('60'))
})

test('contextBar field includes bar() helper', () => {
  const s = generateScript({ ...base, fields: ['contextBar'] })
  assert.ok(s.includes('bar()'))
})

test('contextBar omitted when not in fields', () => {
  const s = generateScript({ ...base, fields: ['model'] })
  assert.ok(!s.includes('context:'))
})

test('rateLimitBars field includes fetch logic', () => {
  const s = generateScript({ ...base, fields: ['rateLimitBars'] })
  assert.ok(s.includes('USAGE_CACHE'))
  assert.ok(s.includes('fetch_usage_bg'))
})

test('no rateLimitBars means no fetch logic', () => {
  const s = generateScript({ ...base, fields: ['model', 'contextBar'] })
  assert.ok(!s.includes('fetch_usage_bg'))
})

test('linesChanged field uses lines_added variable', () => {
  const s = generateScript({ ...base, fields: ['linesChanged'] })
  assert.ok(s.includes('lines_added'))
})

test('multi layout produces line1 and line2 variables', () => {
  const s = generateScript({ fields: ['model', 'contextBar'], layout: 'multi', colorStyle: 'monochrome', thresholds: { yellow: 50, red: 80 } })
  assert.ok(s.includes('line1='))
  assert.ok(s.includes('line2='))
})

test('single layout produces only line1 variable', () => {
  const s = generateScript({ fields: ['model', 'tokenCounts'], layout: 'single', colorStyle: 'monochrome', thresholds: { yellow: 50, red: 80 } })
  assert.ok(s.includes('line1='))
  assert.ok(!s.includes('line2='))
})
