#!/bin/bash
# Generated by claude-statusline wizard — re-run `npx @alejandroroman/cc-statusline` to reconfigure
set -euo pipefail

G='\033[32m'
Y='\033[33m'
D='\033[2m'
RED='\033[31m'
R='\033[0m'

input=$(cat)

parsed=""
parsed=$(echo "$input" | jq -r '[
  (.model.display_name // "Unknown"),
  (.context_window.total_input_tokens // 0),
  (.context_window.total_output_tokens // 0),
  (.context_window.context_window_size // 200000),
  (.context_window.used_percentage // 0),
  (.context_window.remaining_percentage // 0),
  (.cost.total_lines_added // 0),
  (.cost.total_lines_removed // 0),
  (.version // "unknown"),
  ((.rate_limits.five_hour.used_percentage // -1) | floor),
  ((.rate_limits.five_hour.resets_at // "null") | tostring),
  ((.rate_limits.seven_day.used_percentage // -1) | floor),
  ((.rate_limits.seven_day.resets_at // "null") | tostring)
] | @tsv' 2>/dev/null) || parsed=""

if [[ -n "$parsed" ]]; then
  IFS=$'\t' read -r model_name total_input total_output context_size used_pct remaining_pct \
       lines_added lines_removed cc_version five_hour_pct_raw five_hour_reset_raw \
       weekly_pct_raw weekly_reset_raw <<< "$parsed"
else
  model_name="Unknown"; total_input=0; total_output=0; context_size=200000
  used_pct=0; remaining_pct=0; lines_added=0; lines_removed=0; cc_version="unknown"
  five_hour_pct_raw=-1; five_hour_reset_raw=""; weekly_pct_raw=-1; weekly_reset_raw=""
fi

total_tokens=$((total_input + total_output))
remaining_tokens=$((context_size - total_tokens))
[[ "$remaining_tokens" -lt 0 ]] && remaining_tokens=0
total_k=$((total_tokens / 1000))
context_k=$((context_size / 1000))

fmt() { echo "$1" | sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta'; }

bar() {
  local pct="${1%%.*}"
  if ! [[ "$pct" =~ ^-?[0-9]+$ ]]; then echo "○○○○○○○○○○"; return; fi
  [[ "$pct" -gt 100 ]] && pct=100
  [[ "$pct" -lt 0 ]] && pct=0
  local filled=$((pct / 10))
  local empty=$((10 - filled)) out=""
  for ((i = 0; i < filled; i++)); do out+="●"; done
  for ((i = 0; i < empty; i++)); do out+="○"; done
  echo "$out"
}

color_for_pct() {
  local pct="${1%%.*}"
  if ! [[ "$pct" =~ ^[0-9]+$ ]]; then echo "$D"; return; fi
  if [[ "$pct" -ge 80 ]]; then echo "$RED"
  elif [[ "$pct" -ge 50 ]]; then echo "$Y"
  else echo "$G"; fi
}

format_reset_time() {
  local raw="$1"
  if [[ -z "$raw" ]] || [[ "$raw" == "null" ]]; then echo "---"; return; fi

  if [[ "$raw" =~ ^[0-9]+$ ]]; then
    if [[ "$(uname -s)" == "Darwin" ]]; then
      date -r "$raw" "+%l:%M%p %b %d" 2>/dev/null | tr "[:upper:]" "[:lower:]" | sed "s/^ //" || echo "---"
    else
      date -d "@$raw" "+%l:%M%p %b %d" 2>/dev/null | tr "[:upper:]" "[:lower:]" | sed "s/^ //" || echo "---"
    fi
    return
  fi

  local clean
  clean=$(echo "$raw" | sed 's/\.[0-9]*+/+/' | sed 's/\.[0-9]*Z/Z/')
  local result=""
  if [[ "$(uname -s)" == "Darwin" ]]; then
    local no_tz
    no_tz=$(echo "$clean" | sed 's/[+-][0-9][0-9]:[0-9][0-9]$//' | sed 's/Z$//')
    local epoch
    epoch=$(TZ=UTC date -j -f "%Y-%m-%dT%H:%M:%S" "$no_tz" "+%s" 2>/dev/null) || { echo "---"; return; }
    result=$(date -j -r "$epoch" "+%l:%M%p %b %d" 2>/dev/null) || { echo "---"; return; }
  else
    result=$(date -d "$clean" "+%l:%M%p %b %d" 2>/dev/null) || { echo "---"; return; }
  fi
  echo "$result" | tr '[:upper:]' '[:lower:]' | sed 's/^ //'
}

five_hour_pct="---"; weekly_pct="---"; five_hour_reset="---"; weekly_reset="---"
[[ "$five_hour_pct_raw" != "-1" ]] && five_hour_pct="$five_hour_pct_raw"
[[ "$weekly_pct_raw" != "-1" ]] && weekly_pct="$weekly_pct_raw"
[[ -n "$five_hour_reset_raw" ]] && five_hour_reset=$(format_reset_time "$five_hour_reset_raw")
[[ -n "$weekly_reset_raw" ]] && weekly_reset=$(format_reset_time "$weekly_reset_raw")

line1="${G}${model_name}${R} | ${G}${total_k}k / ${context_k}k${R} | ${Y}${used_pct}% used $(fmt $total_tokens)${R} | ${G}${remaining_pct}% remain $(fmt $remaining_tokens)${R}"
if [[ "$lines_added" != "0" ]] || [[ "$lines_removed" != "0" ]]; then
  line1+=" | ${G}+${lines_added}${R}/${RED}-${lines_removed}${R}"
fi
line2=""
append_line2() {
  if [[ -n "$line2" ]]; then line2+=" | $1"; else line2="$1"; fi
}
append_line2 "$(color_for_pct "$used_pct")context: $(bar "$used_pct") ${used_pct}%${R}"
if [[ "$five_hour_pct" == "---" ]]; then
  append_line2 "${D}5-hour: $(bar "---") ---${R}"
else
  append_line2 "$(color_for_pct "$five_hour_pct")5-hour: $(bar "$five_hour_pct") ${five_hour_pct}%${R}"
fi
if [[ "$weekly_pct" == "---" ]]; then
  append_line2 "${D}weekly: $(bar "---") ---${R}"
else
  append_line2 "$(color_for_pct "$weekly_pct")weekly: $(bar "$weekly_pct") ${weekly_pct}%${R}"
fi
line3="${D}5-hour resets ${five_hour_reset}${R} | ${D}weekly resets ${weekly_reset}${R}"
printf "%b\n%b\n%b\n" "$line1" "$line2" "$line3"
