// lib/generate.js
// Pure function: config -> bash script string. No I/O.

export function generateScript(config) {
  const { fields, layout, colorStyle, thresholds = { yellow: 50, red: 80 } } = config

  const hasColors       = colorStyle !== 'monochrome'
  const needsBar        = fields.includes('contextBar') || fields.includes('rateLimitBars')
  const needsFmt        = fields.includes('tokenCounts') || fields.includes('usedPct') || fields.includes('remainingPct')
  const needsRateLimits = fields.includes('rateLimitBars') || fields.includes('resetTimes')

  const s = []

  // Preamble
  s.push('#!/bin/bash')
  s.push('# Generated by claude-statusline wizard — re-run `npx claude-statusline` to reconfigure')
  s.push('set -euo pipefail')
  s.push('')

  // Colors
  if (hasColors) {
    s.push("G='\\033[32m'")
    s.push("Y='\\033[33m'")
    s.push("D='\\033[2m'")
    s.push("RED='\\033[31m'")
    s.push("R='\\033[0m'")
    s.push('')
  }

  // Rate limit cache paths
  if (needsRateLimits) {
    s.push('CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/claude-statusline"')
    s.push('USAGE_CACHE="$CACHE_DIR/usage.json"')
    s.push('USAGE_LOCK="$CACHE_DIR/usage.lock"')
    s.push('CACHE_MAX_AGE=60')
    s.push('CRED_FILE="$HOME/.claude/.credentials.json"')
    s.push('mkdir -p "$CACHE_DIR"')
    s.push('chmod 700 "$CACHE_DIR" 2>/dev/null || true')
    s.push('')
  }

  // Read stdin + parse (always parse superset — one cheap jq call)
  s.push('input=$(cat)')
  s.push('')
  s.push('parsed=""')
  s.push("parsed=$(echo \"$input\" | jq -r '[")
  s.push('  (.model.display_name // "Unknown"),')
  s.push('  (.context_window.total_input_tokens // 0),')
  s.push('  (.context_window.total_output_tokens // 0),')
  s.push('  (.context_window.context_window_size // 200000),')
  s.push('  (.context_window.used_percentage // 0),')
  s.push('  (.context_window.remaining_percentage // 0),')
  s.push('  (.cost.total_lines_added // 0),')
  s.push('  (.cost.total_lines_removed // 0),')
  s.push('  (.version // "unknown")')
  s.push("] | @tsv' 2>/dev/null) || parsed=\"\"")
  s.push('')
  s.push('if [[ -n "$parsed" ]]; then')
  s.push("  IFS=$'\\t' read -r model_name total_input total_output context_size used_pct remaining_pct \\")
  s.push('       lines_added lines_removed cc_version <<< "$parsed"')
  s.push('else')
  s.push('  model_name="Unknown"; total_input=0; total_output=0; context_size=200000')
  s.push('  used_pct=0; remaining_pct=0; lines_added=0; lines_removed=0; cc_version="unknown"')
  s.push('fi')
  s.push('')
  s.push('total_tokens=$((total_input + total_output))')
  s.push('remaining_tokens=$((context_size - total_tokens))')
  s.push('total_k=$((total_tokens / 1000))')
  s.push('context_k=$((context_size / 1000))')
  s.push('')

  // Helpers
  if (needsFmt) {
    s.push("fmt() { echo \"$1\" | sed -e :a -e 's/\\(.*[0-9]\\)\\([0-9]\\{3\\}\\)/\\1,\\2/;ta'; }")
    s.push('')
  }

  if (needsBar) {
    s.push('bar() {')
    s.push('  local pct="${1%%.*}"')
    s.push('  if ! [[ "$pct" =~ ^-?[0-9]+$ ]]; then echo "○○○○○○○○○○"; return; fi')
    s.push('  [[ "$pct" -gt 100 ]] && pct=100')
    s.push('  [[ "$pct" -lt 0 ]] && pct=0')
    s.push('  local filled=$((pct / 10))')
    s.push('  local empty=$((10 - filled)) out=""')
    s.push('  for ((i = 0; i < filled; i++)); do out+="●"; done')
    s.push('  for ((i = 0; i < empty; i++)); do out+="○"; done')
    s.push('  echo "$out"')
    s.push('}')
    s.push('')
  }

  if (hasColors) {
    const { yellow, red } = thresholds
    s.push('color_for_pct() {')
    s.push('  local pct="$1"')
    s.push('  if ! [[ "$pct" =~ ^[0-9]+$ ]]; then echo "$D"; return; fi')
    s.push(`  if [[ "$pct" -ge ${red} ]]; then echo "$RED"`)
    s.push(`  elif [[ "$pct" -ge ${yellow} ]]; then echo "$Y"`)
    s.push('  else echo "$G"; fi')
    s.push('}')
    s.push('')
  }

  // Rate limit fetch block
  if (needsRateLimits) {
    s.push(...rateLimitBlock())
  }

  // Output lines
  if (layout === 'single') {
    s.push(...buildLine1(fields, hasColors))
    s.push('printf "%b\\n" "$line1"')
  } else {
    s.push(...buildLine1(fields, hasColors))
    if (fields.includes('contextBar') || fields.includes('rateLimitBars')) {
      s.push(...buildLine2(fields, hasColors))
    }
    if (fields.includes('resetTimes')) {
      s.push(...buildLine3(hasColors))
    }
    const outputLines = ['line1']
    if (fields.includes('contextBar') || fields.includes('rateLimitBars')) outputLines.push('line2')
    if (fields.includes('resetTimes')) outputLines.push('line3')
    const fmtStr = outputLines.map(() => '%b').join('\\n')
    s.push(`printf "${fmtStr}\\n" ${outputLines.map(l => '"$' + l + '"').join(' ')}`)
  }

  return s.join('\n') + '\n'
}

// ── Private builders ──────────────────────────────────────────────

function buildLine1(fields, hasColors) {
  const [G, Y, R, RED] = hasColors
    ? ['${G}', '${Y}', '${R}', '${RED}']
    : ['', '', '', '']
  const parts = []
  if (fields.includes('model'))        parts.push(`${G}\${model_name}${R}`)
  if (fields.includes('tokenCounts'))  parts.push(`${G}\${total_k}k / \${context_k}k${R}`)
  if (fields.includes('usedPct'))      parts.push(`${Y}\${used_pct}% used $(fmt $total_tokens)${R}`)
  if (fields.includes('remainingPct')) parts.push(`${G}\${remaining_pct}% remain $(fmt $remaining_tokens)${R}`)
  const lines = [`line1="${parts.join(' | ')}"`]
  if (fields.includes('linesChanged')) {
    lines.push(`if [[ "$lines_added" != "0" ]] || [[ "$lines_removed" != "0" ]]; then`)
    lines.push(`  line1+=" | ${G}+\${lines_added}${R}/${RED}-\${lines_removed}${R}"`)
    lines.push('fi')
  }
  return lines
}

function buildLine2(fields, hasColors) {
  const [D, R] = hasColors ? ['${D}', '${R}'] : ['', '']
  const lines = []
  if (fields.includes('contextBar')) {
    const color = hasColors ? '$(color_for_pct "$used_pct")' : ''
    lines.push(`line2="${color}context: $(bar "$used_pct") \${used_pct}%${R}"`)
  } else {
    lines.push('line2=""')
  }
  if (fields.includes('rateLimitBars')) {
    const fhColor = hasColors ? '$(color_for_pct "$five_hour_pct")' : ''
    const wkColor = hasColors ? '$(color_for_pct "$weekly_pct")' : ''
    lines.push(`if [[ "$five_hour_pct" == "---" ]]; then`)
    lines.push(`  line2+=" | ${D}5-hour: $(bar "---") ---${R}"`)
    lines.push('else')
    lines.push(`  line2+=" | ${fhColor}5-hour: $(bar "$five_hour_pct") \${five_hour_pct}%${R}"`)
    lines.push('fi')
    lines.push(`if [[ "$weekly_pct" == "---" ]]; then`)
    lines.push(`  line2+=" | ${D}weekly: $(bar "---") ---${R}"`)
    lines.push('else')
    lines.push(`  line2+=" | ${wkColor}weekly: $(bar "$weekly_pct") \${weekly_pct}%${R}"`)
    lines.push('fi')
  }
  return lines
}

function buildLine3(hasColors) {
  const [D, R] = hasColors ? ['${D}', '${R}'] : ['', '']
  return [`line3="${D}5-hour resets \${five_hour_reset}${R} | ${D}weekly resets \${weekly_reset}${R}"`]
}

function rateLimitBlock() {
  return [
    'format_reset_time() {',
    '  local iso="$1"',
    '  if [[ -z "$iso" ]] || [[ "$iso" == "null" ]]; then echo "---"; return; fi',
    '  local clean',
    "  clean=$(echo \"$iso\" | sed 's/\\.[0-9]*+/+/' | sed 's/\\.[0-9]*Z/Z/')",
    '  local result=""',
    '  if [[ "$(uname -s)" == "Darwin" ]]; then',
    '    local no_tz',
    "    no_tz=$(echo \"$clean\" | sed 's/[+-][0-9][0-9]:[0-9][0-9]$//' | sed 's/Z$//')",
    '    local epoch',
    '    epoch=$(TZ=UTC date -j -f "%Y-%m-%dT%H:%M:%S" "$no_tz" "+%s" 2>/dev/null) || { echo "---"; return; }',
    '    result=$(date -j -r "$epoch" "+%l:%M%p %b %d" 2>/dev/null) || { echo "---"; return; }',
    '  else',
    '    result=$(date -d "$clean" "+%l:%M%p %b %d" 2>/dev/null) || { echo "---"; return; }',
    '  fi',
    "  echo \"$result\" | tr '[:upper:]' '[:lower:]' | sed 's/^ //'",
    '}',
    '',
    'get_file_age() {',
    '  local file="$1"',
    '  if [[ "$(uname -s)" == "Darwin" ]]; then',
    "    stat -f '%m' \"$file\" 2>/dev/null || echo 999999",
    '  else',
    "    stat -c '%Y' \"$file\" 2>/dev/null || echo 999999",
    '  fi',
    '}',
    '',
    'get_access_token() {',
    '  if command -v security &>/dev/null; then',
    '    local j; j=$(security find-generic-password -s "Claude Code-credentials" -w 2>/dev/null) || true',
    "    if [[ -n \"$j\" ]]; then",
    "      local t; t=$(echo \"$j\" | jq -r '.claudeAiOauth.accessToken // empty' 2>/dev/null)",
    '      [[ -n "$t" ]] && { echo "$t"; return 0; }',
    '    fi',
    '  fi',
    '  [[ -f "$CRED_FILE" ]] && jq -r \'.claudeAiOauth.accessToken // empty\' "$CRED_FILE" 2>/dev/null && return 0',
    '  return 1',
    '}',
    '',
    'fetch_usage_bg() {',
    '  mkdir "$USAGE_LOCK" 2>/dev/null || {',
    '    local age; age=$(get_file_age "$USAGE_LOCK")',
    '    [[ "$age" -lt 30 ]] && return 0',
    '    rm -rf "$USAGE_LOCK"; mkdir "$USAGE_LOCK" 2>/dev/null || return 0',
    '  }',
    '  (',
    "    trap 'rm -rf \"$USAGE_LOCK\"' EXIT",
    '    local token; token=$(get_access_token) || exit 1',
    '    local tf; tf=$(mktemp "$CACHE_DIR/tok.XXXXXX"); chmod 600 "$tf"',
    "    printf 'Authorization: Bearer %s' \"$token\" > \"$tf\"",
    '    local resp; resp=$(curl -s --max-time 5 -H @"$tf" \\',
    '      -H "anthropic-beta: oauth-2025-04-20" -H "Accept: application/json" \\',
    '      "https://api.anthropic.com/api/oauth/usage" 2>/dev/null)',
    '    rm -f "$tf"',
    "    if echo \"$resp\" | jq -e '.five_hour' &>/dev/null; then",
    '      local tmp; tmp=$(mktemp "$CACHE_DIR/cache.XXXXXX")',
    '      echo "$resp" > "$tmp" && mv "$tmp" "$USAGE_CACHE"',
    '    fi',
    '  ) &',
    '  disown 2>/dev/null',
    '}',
    '',
    'five_hour_pct="---"; weekly_pct="---"; five_hour_reset="---"; weekly_reset="---"',
    'if [[ -f "$USAGE_CACHE" ]]; then',
    "  age=$(get_file_age \"$USAGE_CACHE\")",
    "  u=$(jq -r '[(.five_hour.utilization//-1|floor),(.five_hour.resets_at//\"\"),",
    '    ((.seven_day.utilization//-1)|floor),(.seven_day.resets_at//"")]',
    '    | @tsv\' "$USAGE_CACHE" 2>/dev/null) || u=""',
    '  if [[ -n "$u" ]]; then',
    "    IFS=$'\\t' read -r fh_p fh_r wk_p wk_r <<< \"$u\"",
    '    [[ "$fh_p" != "-1" ]] && five_hour_pct="$fh_p"',
    '    [[ "$wk_p" != "-1" ]] && weekly_pct="$wk_p"',
    '    [[ -n "$fh_r" ]] && five_hour_reset=$(format_reset_time "$fh_r")',
    '    [[ -n "$wk_r" ]] && weekly_reset=$(format_reset_time "$wk_r")',
    '  fi',
    '  [[ "$age" -ge "$CACHE_MAX_AGE" ]] && fetch_usage_bg',
    'else',
    '  fetch_usage_bg',
    'fi',
    '',
  ]
}
