// lib/generate.js
// Pure function: config -> bash script string. No I/O.

export function generateScript(config) {
  const { fields, layout, colorStyle, thresholds = { yellow: 50, red: 80 } } = config

  const hasColors       = colorStyle !== 'monochrome'
  const needsBar        = fields.includes('contextBar') || fields.includes('rateLimitBars')
  const needsFmt        = fields.includes('tokenCounts') || fields.includes('usedPct') || fields.includes('remainingPct')
  const needsRateLimits = fields.includes('rateLimitBars') || fields.includes('resetTimes')

  const s = []

  // Preamble
  s.push('#!/bin/bash')
  s.push('# Generated by claude-statusline wizard — re-run `npx @alejandroroman/cc-statusline` to reconfigure')
  s.push('set -euo pipefail')
  s.push('')

  // Colors
  if (hasColors) {
    s.push("G='\\033[32m'")
    s.push("Y='\\033[33m'")
    s.push("D='\\033[2m'")
    s.push("RED='\\033[31m'")
    s.push("R='\\033[0m'")
    s.push('')
  }

  // Read stdin + parse (always parse superset — one cheap jq call)
  s.push('input=$(cat)')
  s.push('')
  s.push('parsed=""')
  s.push("parsed=$(echo \"$input\" | jq -r '[")
  s.push('  (.model.display_name // "Unknown"),')
  s.push('  (.context_window.total_input_tokens // 0),')
  s.push('  (.context_window.total_output_tokens // 0),')
  s.push('  (.context_window.context_window_size // 200000),')
  s.push('  (.context_window.used_percentage // 0),')
  s.push('  (.context_window.remaining_percentage // 0),')
  s.push('  (.cost.total_lines_added // 0),')
  s.push('  (.cost.total_lines_removed // 0),')
  s.push('  (.version // "unknown"),')
  s.push('  ((.rate_limits.five_hour.used_percentage // -1) | floor),')
  s.push('  ((.rate_limits.five_hour.resets_at // "null") | tostring),')
  s.push('  ((.rate_limits.seven_day.used_percentage // -1) | floor),')
  s.push('  ((.rate_limits.seven_day.resets_at // "null") | tostring)')
  s.push("] | @tsv' 2>/dev/null) || parsed=\"\"")
  s.push('')
  s.push('if [[ -n "$parsed" ]]; then')
  s.push("  IFS=$'\\t' read -r model_name total_input total_output context_size used_pct remaining_pct \\")
  s.push('       lines_added lines_removed cc_version five_hour_pct_raw five_hour_reset_raw \\')
  s.push('       weekly_pct_raw weekly_reset_raw <<< "$parsed"')
  s.push('else')
  s.push('  model_name="Unknown"; total_input=0; total_output=0; context_size=200000')
  s.push('  used_pct=0; remaining_pct=0; lines_added=0; lines_removed=0; cc_version="unknown"')
  s.push('  five_hour_pct_raw=-1; five_hour_reset_raw=""; weekly_pct_raw=-1; weekly_reset_raw=""')
  s.push('fi')
  s.push('')
  s.push('total_tokens=$((total_input + total_output))')
  s.push('remaining_tokens=$((context_size - total_tokens))')
  s.push('[[ "$remaining_tokens" -lt 0 ]] && remaining_tokens=0')
  s.push('total_k=$((total_tokens / 1000))')
  s.push('context_k=$((context_size / 1000))')
  s.push('')

  // Helpers
  if (needsFmt) {
    s.push("fmt() { echo \"$1\" | sed -e :a -e 's/\\(.*[0-9]\\)\\([0-9]\\{3\\}\\)/\\1,\\2/;ta'; }")
    s.push('')
  }

  if (needsBar) {
    s.push('bar() {')
    s.push('  local pct="${1%%.*}"')
    s.push('  if ! [[ "$pct" =~ ^-?[0-9]+$ ]]; then echo "○○○○○○○○○○"; return; fi')
    s.push('  [[ "$pct" -gt 100 ]] && pct=100')
    s.push('  [[ "$pct" -lt 0 ]] && pct=0')
    s.push('  local filled=$((pct / 10))')
    s.push('  local empty=$((10 - filled)) out=""')
    s.push('  for ((i = 0; i < filled; i++)); do out+="●"; done')
    s.push('  for ((i = 0; i < empty; i++)); do out+="○"; done')
    s.push('  echo "$out"')
    s.push('}')
    s.push('')
  }

  if (hasColors) {
    const { yellow, red } = thresholds
    s.push('color_for_pct() {')
    s.push('  local pct="${1%%.*}"')
    s.push('  if ! [[ "$pct" =~ ^[0-9]+$ ]]; then echo "$D"; return; fi')
    s.push(`  if [[ "$pct" -ge ${red} ]]; then echo "$RED"`)
    s.push(`  elif [[ "$pct" -ge ${yellow} ]]; then echo "$Y"`)
    s.push('  else echo "$G"; fi')
    s.push('}')
    s.push('')
  }

  // Rate limit values come from Claude Code statusLine stdin JSON.
  if (needsRateLimits) {
    s.push(...rateLimitBlock())
  }

  // Output lines
  if (layout === 'single') {
    s.push(...buildLine1(fields, hasColors))
    s.push('printf "%b\\n" "$line1"')
  } else {
    s.push(...buildLine1(fields, hasColors))
    if (fields.includes('contextBar') || fields.includes('rateLimitBars')) {
      s.push(...buildLine2(fields, hasColors))
    }
    if (fields.includes('resetTimes')) {
      s.push(...buildLine3(hasColors))
    }
    const outputLines = ['line1']
    if (fields.includes('contextBar') || fields.includes('rateLimitBars')) outputLines.push('line2')
    if (fields.includes('resetTimes')) outputLines.push('line3')
    const fmtStr = outputLines.map(() => '%b').join('\\n')
    s.push(`printf "${fmtStr}\\n" ${outputLines.map(l => '"$' + l + '"').join(' ')}`)
  }

  return s.join('\n') + '\n'
}

// ── Private builders ──────────────────────────────────────────────

function buildLine1(fields, hasColors) {
  const [G, Y, R, RED] = hasColors
    ? ['${G}', '${Y}', '${R}', '${RED}']
    : ['', '', '', '']
  const parts = []
  if (fields.includes('model'))        parts.push(`${G}\${model_name}${R}`)
  if (fields.includes('tokenCounts'))  parts.push(`${G}\${total_k}k / \${context_k}k${R}`)
  if (fields.includes('usedPct'))      parts.push(`${Y}\${used_pct}% used $(fmt $total_tokens)${R}`)
  if (fields.includes('remainingPct')) parts.push(`${G}\${remaining_pct}% remain $(fmt $remaining_tokens)${R}`)
  const lines = [`line1="${parts.join(' | ')}"`]
  if (fields.includes('linesChanged')) {
    lines.push(`if [[ "$lines_added" != "0" ]] || [[ "$lines_removed" != "0" ]]; then`)
    lines.push(`  line1+=" | ${G}+\${lines_added}${R}/${RED}-\${lines_removed}${R}"`)
    lines.push('fi')
  }
  return lines
}

function buildLine2(fields, hasColors) {
  const [D, R] = hasColors ? ['${D}', '${R}'] : ['', '']
  const lines = []
  lines.push('line2=""')
  lines.push('append_line2() {')
  lines.push('  if [[ -n "$line2" ]]; then line2+=" | $1"; else line2="$1"; fi')
  lines.push('}')
  if (fields.includes('contextBar')) {
    const color = hasColors ? '$(color_for_pct "$used_pct")' : ''
    lines.push(`append_line2 "${color}context: $(bar "$used_pct") \${used_pct}%${R}"`)
  }
  if (fields.includes('rateLimitBars')) {
    const fhColor = hasColors ? '$(color_for_pct "$five_hour_pct")' : ''
    const wkColor = hasColors ? '$(color_for_pct "$weekly_pct")' : ''
    lines.push(`if [[ "$five_hour_pct" == "---" ]]; then`)
    lines.push(`  append_line2 "${D}5-hour: $(bar "---") ---${R}"`)
    lines.push('else')
    lines.push(`  append_line2 "${fhColor}5-hour: $(bar "$five_hour_pct") \${five_hour_pct}%${R}"`)
    lines.push('fi')
    lines.push(`if [[ "$weekly_pct" == "---" ]]; then`)
    lines.push(`  append_line2 "${D}weekly: $(bar "---") ---${R}"`)
    lines.push('else')
    lines.push(`  append_line2 "${wkColor}weekly: $(bar "$weekly_pct") \${weekly_pct}%${R}"`)
    lines.push('fi')
  }
  return lines
}

function buildLine3(hasColors) {
  const [D, R] = hasColors ? ['${D}', '${R}'] : ['', '']
  return [`line3="${D}5-hour resets \${five_hour_reset}${R} | ${D}weekly resets \${weekly_reset}${R}"`]
}

function rateLimitBlock() {
  return [
    'format_reset_time() {',
    '  local raw="$1"',
    '  if [[ -z "$raw" ]] || [[ "$raw" == "null" ]]; then echo "---"; return; fi',
    '',
    '  if [[ "$raw" =~ ^[0-9]+$ ]]; then',
    '    if [[ "$(uname -s)" == "Darwin" ]]; then',
    '      date -r "$raw" "+%l:%M%p %b %d" 2>/dev/null | tr "[:upper:]" "[:lower:]" | sed "s/^ //" || echo "---"',
    '    else',
    '      date -d "@$raw" "+%l:%M%p %b %d" 2>/dev/null | tr "[:upper:]" "[:lower:]" | sed "s/^ //" || echo "---"',
    '    fi',
    '    return',
    '  fi',
    '',
    '  local clean',
    "  clean=$(echo \"$raw\" | sed 's/\\.[0-9]*+/+/' | sed 's/\\.[0-9]*Z/Z/')",
    '  local result=""',
    '  if [[ "$(uname -s)" == "Darwin" ]]; then',
    '    local no_tz',
    "    no_tz=$(echo \"$clean\" | sed 's/[+-][0-9][0-9]:[0-9][0-9]$//' | sed 's/Z$//')",
    '    local epoch',
    '    epoch=$(TZ=UTC date -j -f "%Y-%m-%dT%H:%M:%S" "$no_tz" "+%s" 2>/dev/null) || { echo "---"; return; }',
    '    result=$(date -j -r "$epoch" "+%l:%M%p %b %d" 2>/dev/null) || { echo "---"; return; }',
    '  else',
    '    result=$(date -d "$clean" "+%l:%M%p %b %d" 2>/dev/null) || { echo "---"; return; }',
    '  fi',
    "  echo \"$result\" | tr '[:upper:]' '[:lower:]' | sed 's/^ //'",
    '}',
    '',
    'five_hour_pct="---"; weekly_pct="---"; five_hour_reset="---"; weekly_reset="---"',
    '[[ "$five_hour_pct_raw" != "-1" ]] && five_hour_pct="$five_hour_pct_raw"',
    '[[ "$weekly_pct_raw" != "-1" ]] && weekly_pct="$weekly_pct_raw"',
    '[[ -n "$five_hour_reset_raw" ]] && five_hour_reset=$(format_reset_time "$five_hour_reset_raw")',
    '[[ -n "$weekly_reset_raw" ]] && weekly_reset=$(format_reset_time "$weekly_reset_raw")',
    '',
  ]
}
